# Generated by Django 4.0.3 on 2025-11-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0008_product_category_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Packing', 'Packing'), ('Raw', 'Raw')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default='1', max_length=2),
        ),
    ]
